
source 'https://github.com/wuzhenli/WZLPodRepo.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

platform :ios, '8.0'

target 'WZLMaseBusiness_Example' do
  pod 'WZLMaseBusiness', :path => '../'

  target 'WZLMaseBusiness_Tests' do
    inherit! :search_paths

    
  end
end
